### ISSUE TITLE
Broken link in the tutorial - component chapter

### ISSUE THREAD

**Issue by ghost** [ng-girls/todo-list-tutorial#228]
In this page 
https://ng-girls.gitbook.io/todo-list-tutorial/workshop-todo-list/a-new-component/stackblitz
the link to the "#3 component chapter" 
https://ng-girls.gitbook.io/todo-list-tutorial/component#inline-template
is broken

The same, at the end, the link "continue the tutorial"
https://ng-girls.gitbook.io/todo-list-tutorial/a-new-component/README.md
is broken

I think it is missing "workshop-todo-list/" in the URLs

**Comment by willi84** [comment]
done
