### ISSUE TITLE
Broken link in the tutorial - Interface (Stackblitz instructions)

### ISSUE THREAD

**Issue by ghost** [ng-girls/todo-list-tutorial#229]
Similar to issue #228:

In this page
https://ng-girls.gitbook.io/todo-list-tutorial/workshop-todo-list/interface/stackblitz
the link to "continue the tutorial"
https://ng-girls.gitbook.io/todo-list-tutorial/interface/README.md
is broken

**Comment by willi84** [comment]
fixed
